### ISSUE TITLE
How to send commands with delays between them?

### ISSUE THREAD

**Issue by slaff** [mikee47/Sming-Graphics#1]
I am trying to implement a driver for the [ST7789V display](https://www.newhavendisplay.com/appnotes/datasheets/LCDs/ST7789V.pdf). Some of the available commands require a minimum wait time before the next command is sent. For example take a look at page 163 and the software reset command:
```
It will be necessary to wait 5msec before sending new command following software reset.
The display module loads all display suppliers’ factory default values to the registers during this 5msec.
If software reset is sent during sleep in mode, it will be necessary to wait 120msec before sending sleep out command
```

Is it possible to describe such a minimum wait time between the commands in a SpiDisplayList ? Is it possible to define a "meta" command that marks such a minimum required delay? For example:

```C++
DEFINE_RB_ARRAY(										
	displayInitData,										
	DEFINE_RB_COMMAND(ST7735_SWRESET, 0)  // software reset
        DEFINE_RB_COMMAND(LIST_DELAY, 1, 5) // wait 5 ms before the next command is sent 
	DEFINE_RB_COMMAND(ST7735_SLPOUT, 0)	//Out of sleep mode
        DEFINE_RB_COMMAND(LIST_DELAY, 1, 5) // It will be necessary to wait 5msec before sending any new commands to a //display module following this command to
// allow time for the supply voltages and clock circuits to stabilize.
        DEFINE_RB_COMMAND(ST7735_COLMOD, 1, 0x05) // Set color mode: 16 bit mode...
)

**Comment by mikee47** [comment]
Short answer: no. just handle the delays manually - see `ILI9341::begin()`.

Long answer: yes. As with the ILI9341, the only commands with extended timing requirements are SWRESET, SLPIN and SLPOUT. As these are only used during initialisation, waiting around for 120ms or so isn't much of an issue.

Adding a delay to the DisplayList would, by itself, provide very little benefit. However, a fully asynchronous initialisation sequence would allow other stuff to get done in those 120+ ms. 
The `begin()` method could have a callback parameter to notify the application when the display is ready.

DisplayLists are executed in interrupt context - see `SpiDisplayList::fillRequest()`, and we'd need a timer to handle the delay.

Question is whether the additional complexity and IRAM/RAM usage is justified...

**Comment by mikee47** [comment]
@slaff I've come up with a compromise approach to supporting initialisation lists, see PR #2. The new `SpiDisplay` base class provides an `execute` method which handles the delays directly.

**Comment by slaff** [comment]
@mikee47 Great! I will look later today at your PR. Meanwhile I saw that there are common features between displays that support MIPI and decided to create a MIPI display as a base and extend ILI9341 and ST7789V display.

You can take a look at the proposed changes here: https://github.com/mikee47/Sming-Graphics/compare/feature/esp32...slaff:feature/mipi-display?expand=1. I was just experimenting up to now. The code might compile but I am not sure if it will work on a real-device. It is still quite raw.

Feel free to improve the code. It would be really useful to have relatively easy way to add more MIPI display drivers and abstract most of the common code.

**Comment by mikee47** [comment]
@slaff Thanks, I wasn't aware that the ILI9341 supported any common standard! No mention of it in the datasheet, but if it works then fantastic!
